### ISSUE TITLE
能用markdown格式写一下吗

### ISSUE THREAD

**Issue by wgqhandsome** [xizeyoupan/study#1]
朋友
  你好：

图片格式不怎么清晰，能转化成markdown格式吗。

thanks

**Comment by xizeyoupan** [comment]
> 朋友
> 你好：
> 
> 图片格式不怎么清晰，能转化成markdown格式吗。
> 
> thanks

图片看清是肯定没问题的。
github本身并不支持LaTeX语法，只能通过插入公式的图片等方式实现，费力麻烦。
如果你能写数学公式，可以用[这个](https://github.com/xizeyoupan/quick-edit)批量将公式转为图片。
也欢迎提交PR。

**Comment by wgqhandsome** [comment]
有n个元素的集合的子集应该为$2^n$
还有数学中一般句号是用实心点。

**Comment by xizeyoupan** [comment]
> 有n个元素的集合的子集应该为$2^n$

感谢斧正！
